//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSteganographyApplication.Steganography {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Steganography.IHideAndSeek")]
    public interface IHideAndSeek {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideAndSeek/hideMessage", ReplyAction="http://tempuri.org/IHideAndSeek/hideMessageResponse")]
        byte[] hideMessage(string msg, string key, byte[] cover, string encryptType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideAndSeek/hideMessage", ReplyAction="http://tempuri.org/IHideAndSeek/hideMessageResponse")]
        System.Threading.Tasks.Task<byte[]> hideMessageAsync(string msg, string key, byte[] cover, string encryptType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideAndSeek/seekMessage", ReplyAction="http://tempuri.org/IHideAndSeek/seekMessageResponse")]
        string seekMessage(string key, byte[] coverWithData, string encryptType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideAndSeek/seekMessage", ReplyAction="http://tempuri.org/IHideAndSeek/seekMessageResponse")]
        System.Threading.Tasks.Task<string> seekMessageAsync(string key, byte[] coverWithData, string encryptType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHideAndSeekChannel : ImageSteganographyApplication.Steganography.IHideAndSeek, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HideAndSeekClient : System.ServiceModel.ClientBase<ImageSteganographyApplication.Steganography.IHideAndSeek>, ImageSteganographyApplication.Steganography.IHideAndSeek {
        
        public HideAndSeekClient() {
        }
        
        public HideAndSeekClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HideAndSeekClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HideAndSeekClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HideAndSeekClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] hideMessage(string msg, string key, byte[] cover, string encryptType) {
            return base.Channel.hideMessage(msg, key, cover, encryptType);
        }
        
        public System.Threading.Tasks.Task<byte[]> hideMessageAsync(string msg, string key, byte[] cover, string encryptType) {
            return base.Channel.hideMessageAsync(msg, key, cover, encryptType);
        }
        
        public string seekMessage(string key, byte[] coverWithData, string encryptType) {
            return base.Channel.seekMessage(key, coverWithData, encryptType);
        }
        
        public System.Threading.Tasks.Task<string> seekMessageAsync(string key, byte[] coverWithData, string encryptType) {
            return base.Channel.seekMessageAsync(key, coverWithData, encryptType);
        }
    }
}
